GET http://localhost:3333/videos?search=

###

POST http://localhost:3333/videos
Content-Type: application/json

{
    "name":"video third",
    "description":"this is the third video",
    "duration":180
}

###

PUT http://localhost:3333/videos/a9e97d7f-cea5-4b6d-b9f9-46041fdf6264	
Content-Type: application/json

{
    "name":"video 02",
    "description":"EDITED",
    "duration":360
}

###

DELETE http://localhost:3333/videos/