GET https://node-do-zero-fq15.onrender.com?search=

###

POST https://node-do-zero-fq15.onrender.com
Content-Type: application/json

{
    "name":"video third",
    "description":"this is the third video",
    "duration":180
}

###

PUT https://node-do-zero-fq15.onrender.com/
Content-Type: application/json

{
    "name":"video 02",
    "description":"EDITED",
    "duration":360
}

###

DELETE https://node-do-zero-fq15.onrender.com/