GET https://node-do-zero-fq15.onrender.com/videos?search=

###

POST https://node-do-zero-fq15.onrender.com/videos
Content-Type: application/json

{
    "name":"video third",
    "description":"this is the third video",
    "duration":180
}

###

PUT https://node-do-zero-fq15.onrender.com/videos/a9e97d7f-cea5-4b6d-b9f9-46041fdf6264	
Content-Type: application/json

{
    "name":"video 02",
    "description":"EDITED",
    "duration":360
}

###

DELETE https://node-do-zero-fq15.onrender.com/videos/